networkConfig:
  entityIdPrefixes:
    - networks:
        - mainnet
      prefix: ""
    - networks:
        - hardhat
      prefix: local-
entitySettings:
  Campaign:
    useDefault: []
    setters:
      - name: updateCampaignOwner
        fields:
          - owner
      - name: updateCampaignTitle
        fields:
          - title
      - name: updateCampaignClaim
        fields:
          - claim
      - name: updateCampaignDescription
        fields:
          - description
    entityId:
      - name: id
        type: Bytes
  Donation:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  Donor:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  Withdrawal:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  Withdrawer:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  Follow:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
#   OwnershipTransferred:
#     useDefault: []
#     setters: []
#     entityId:
#       - name: id
#         type: Bytes