networkConfig:
  entityIdPrefixes:
    - networks:
        - mainnet
      prefix: ""
    - networks:
        - localhost
      prefix: ""
entitySettings:
  Campaign:
    useDefault: []
    setters:
      - name: updateCampaignOwner
        fields:
          - owner
      - name: updateCampaignTitle
        fields:
          - title
      - name: updateCampaignClaim
        fields:
          - claim
      - name: updateCampaignDescription
        fields:
          - description
    entityId:
      - name: id
        type: Bytes
  Donation:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  Donor:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  Withdrawal:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  Withdrawer:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  Follow:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  CampaignUpdate:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  Idea:
    useDefault: []
    setters:
      - name: updateIdeaParent
        fields:
          - parentId
          - parentIndex
      - name: updateIdeaPosition
        fields:
          - x
          - y
      - name: updateIdeaParentIndex
        fields:
          - parentIndex
      - name: updateIdeaText
        fields:
          - text
      - name: updateIdeaType
        fields:
          - ideaType
    entityId:
      - name: id
        type: Bytes
  SpecialistGroup:
    useDefault: []
    setters:
      - name: updateSpecialistGroupOwner
        fields:
          - owner
      - name: updateSpecialistGroupName
        fields:
          - name
      - name: updateSpecialistGroupSpecification
        fields:
          - specification
      - name: updateSpecialistGroupStatus
        fields:
          - status
    entityId:
      - name: id
        type: Bytes
  SpecialistGroupMembership:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  SpecialistGroupCampaignConnection:
    useDefault: []
    setters: []
    entityId:
      - name: id
        type: Bytes
  TruthRating:
    useDefault: []
    setters:
      - name: updateTruthRating
        fields:
          - ratingScore
          - comments
    entityId:
      - name: id
        type: Bytes